### ISSUE TITLE
Feature: User can create an user account

### ISSUE THREAD

**Issue by Kenneth-Y-Wang** [Kenneth-Y-Wang/ThriveVox#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user will be able to create an account and sign in to the app

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- first by giving the login page, if user does not have an account, they can choose to create an account
- by choosing creating account, user need to type in required information
- after the info is entered, the page will automatically swapped to login in page. 
- type in username and password to enter home page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-01 at 1 16 59 PM](https://user-images.githubusercontent.com/88110300/139736054-0fb2d6cd-9590-4906-bba6-f023a89093ad.png)
![Screen Shot 2021-11-01 at 1 16 46 PM](https://user-images.githubusercontent.com/88110300/139736100-950ac59a-310e-4feb-9fc7-1ec6ef2706d2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to custom schema.sql
- [x] Update `data.sql` to custom data.sql

### ☁️ Server

- [x] Update `server/index.js` file to create the post request for sign-up process
- [x] Test with HTTPie
- [x] check if the database receives the entered data
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a auth-form component
- [x] Create a navbar component
- [x] Create a redirect page component
- [x] Create a library folder for login required decode-token file
- [x] Create appContext js file for react context object
- [x] Create parseRoute function for view swapping 
- [x] Create authorization page with sign-in or sign-up options
- [x] Create page-not-found page
- [x] Create an easy home page
- [x] Update css files for styles and layout
- [x] update all links for index.html for font awesome and google font

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
